const axios = require('axios');

async function verifyApp() {
  const coolifyUrl = 'http://148.116.104.222:8000';
  const apiToken = '1|6PdqwcucWGKSKnK9bykViP4ArSmuXPv8wArWFPBq5b5ba9b0';
  const appUuid = 'tpu9apsacq91bw8ap1iswjwu';

  try {
    const res = await axios.get(`${coolifyUrl}/api/v1/applications/${appUuid}`, {
      headers: { Authorization: `Bearer ${apiToken}` },
    });

    console.log('[App Verified]:');
    console.log('  Name:', res.data.name);
    console.log('  FQDN:', res.data.fqdn);
    console.log('  Ports:', res.data.ports_exposes);
    console.log('  Status:', res.data.status);
    console.log('  Git Branch:', res.data.git_branch);
    console.log('  Git Repo:', res.data.git_repository);

    // Decode labels safely
    if (res.data.custom_labels) {
      try {
        const decoded = Buffer.from(res.data.custom_labels, 'base64').toString('utf-8');
        if (decoded && !decoded.includes('\ufffd')) {
          console.log('\n[Traefik Labels]:\n', decoded);
        } else {
          console.log('\n[Labels]: (binary/regenerated by Coolify - domain change applied via fqdn field)');
        }
      } catch (e) {
        console.log('\n[Labels]: Could not decode');
      }
    }
  } catch (err) {
    console.error('[Error]:', err.response?.data || err.message);
  }
}

verifyApp();
